Owl\Component\User\Model\User:
    exclusion_policy: ALL
    xml_root_name: sylius_user
    properties:
        id:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        username:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart, Secured]
        email:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        enabled:
            expose: true
            type: boolean
            groups: [Default, Detailed]
        roles:
            expose: true
            type: iterable
            groups: [Detailed]
